[package]
name = "pin-project"
version = "0.4.2"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/pin-project"
documentation = "https://docs.rs/pin-project/"
keywords = ["pin", "macros", "attribute"]
categories = ["rust-patterns"]
readme = "README.md"
description = """
A crate for safe and ergonomic pin-projection.
"""

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["pin-project-internal", "tests/ui/auxiliary"]

[dependencies]
pin-project-internal = { version = "=0.4.2", path = "pin-project-internal", default-features = false }

[dev-dependencies]
auxiliary-macros = { version = "0.1", path = "tests/ui/auxiliary" }
trybuild = "1.0"
